routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('/position', 'PositionController');

Route::resource('/vacancy', 'VacancyController');
//Route::get('/vacancy/search', 'VacancyController@search');
Route::post('/vacancy/search', 'VacancyController@search');

Route::post('/candidate/search', 'CandidateController@search');

Route::resource('/candidate', 'CandidateController');

Route::get('/recruited-candidate', 'CandidateController@recruitedCandidate');

Route::resource('/interview-type', 'InterviewTypeController');

Route::resource('/user-type', 'UserTypeController');

Route::resource('/recruiter', 'RecruiterController');

Route::resource('/application', 'ApplicationController');

Route::resource('/interview', 'InterviewController');

Route::get('/interview/create/{id?}', 'InterviewController@create');

Route::post('candidate/{id}/email', 'CandidateController@email')->name('candidate.email');

Route::get('interview/{id}/conduct', 'InterviewController@conduct')->name('interview.conduct');

Route::get('candidate-interview/{id}', 'InterviewController@candidateInterview');

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use App\User;
use DB;
use App\CandidateInfo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
use Auth;
use Mail;

class CandidateController extends Controller
{
    // Returns index View for new candidates
    public function index()
    {
        //SELECT only new candidates
        $candidates = User::
        join('user_types', 'users.user_type_id', '=', 'user_types.id')
            ->where('user_types.id', 1)
            ->paginate(10, array('users.id AS id',
                'users.first_name AS first_name',
                'users.last_name AS last_name'))
        ;
        $type = 1;
        return view('candidate.index', compact('candidates', 'type'));
    }

    // Returns Search View for candidates
    public function search(Request $request)
    {
        $searchTerm = $request->search;
        $candidateType = $request->type;
        $candidates = User::
        join('user_types', 'users.user_type_id', '=', 'user_types.id')
            ->where('user_types.id', $candidateType)
            ->where('first_name', 'like', '%' . $searchTerm . '%')
            ->orWhere('last_name', 'like', '%' . $searchTerm . '%')
            ->paginate(5, array('users.id AS id',
                'users.first_name AS first_name',
                'users.last_name AS last_name'))
        ;

        return view('candidate.search', compact('candidates', 'searchTerm'));
    }

    // Returns index View for recruited candidates
    public function recruitedCandidate()
    {
        $candidates = User::
        join('user_types', 'users.user_type_id', '=', 'user_types.id')
            ->where('user_types.id', 2)
            ->paginate(10, array('users.id AS id',
                'users.first_name AS first_name',
                'users.last_name AS last_name'))
        ;
        $type = 2;
        return view('candidate.index', compact('candidates', 'type'));
    }

    //Returns the show view of the appropriate Candidate
    public function show($id)
    {
        $candidate = collect( DB::select
        ('
            SELECT
            users.id AS id,
            users.first_name AS first_name,
            users.last_name AS last_name,
            users.nic AS nic,
            users.gender AS gender,
            users.dob AS dob,
            users.marital_status AS marital_status,
            users.address AS address,
            users.phone_number AS phone_number,
            users.mobile_number AS mobile_number,
            users.email AS email,
            candidate_infos.cv AS cv,
            candidate_infos.certificates AS certificates,
            user_types.id AS user_type

            FROM
            users,
            user_types,
            candidate_infos

            WHERE
            users.id = "'.$id.'"
            AND
            users.user_type_id = user_types.id
            AND
            candidate_infos.user_id = "'.$id.'"
            AND
            (user_types.id = 1 OR user_types.id = 2)
        '))->first();
        return view('candidate.show', compact('candidate'));
    }

    //Returns the Edit view of the appropriate Candidate
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $candidateInfo = CandidateInfo::where('user_id', '=', $id)->first();
        return view('candidate.edit', compact('user', 'candidateInfo'));
    }

    //When button RECRUIT is pressed, send email to apropriate candidate
    public function email($id)
    {
        $user = User::findOrFail($id);
        $candidateInfo = CandidateInfo::where('user_id', '=', $id)->first();


        $title = "Congratulation!"; // can also appen car name here
        $name = Auth::user()->first_name.' '.Auth::user()->last_name; //or "RecruiterHub"
        if (env('APP_ENV') == "local")
        {
          $email = 'tofy.zubair@gmail.com';
        } else {
          $email = $user->email;
        }

        try {

          Mail::send('email.recruited', ['title' => $title, 'content' => $user], function ($message) use ( $email, $name, $title)
          {
              $message->from('support@recruiterhub.io', 'RecruiterHub Team');
              $message->to($email, $name);
              $message->subject($title);
          });

        } catch (\Exception $e) {

        }

        //set user type to 2
        User::find($id)
          ->update(['user_type_id' => 2]);

        return redirect('candidate')->with('success', 'Candidate Recruited Successfully');
        // return back()->with('success','Email Sent!');
    }

    //Data from the form in the Edit view uses the update function to update data in the database
    public function update(Request $data, $id)
    {
        $user = User::find($id);
        $user->first_name = $data['first_name'];
        $user->last_name = $data['last_name'];
        $user->user_type_id = $data['user_type_id'];
        $user->nic = $data['nic'];
        $user->gender = $data['gender'];
        $user->dob = $data['dob'];
        $user->marital_status = $data['marital_status'];
        $user->address = $data['address'];
        $user->phone_number = $data['phone_number'];
        $user->mobile_number = $data['mobile_number'];
        $user->email = $data['email'];
        $result = $user->save();

        $info = CandidateInfo::where('user_id', $id)->first();
        $info->cv = 'cv.pdf';
        $info->certificates = 'certificates.pdf';
        $info->save();

        if (Auth::user()->user_type_id == 4){
            //If submission of data is successful return to candidates index page with successful message
            if ($result){
                return redirect('candidate')->with('success', 'Candidate Updated');
            }
            //else display fail
            else{
                return back()->with('error','Failed to save!');
            }
        }
        else{
            //If submission of data is successful return to candidate show page with successful message
            if ($result){
                return redirect()->route('candidate.show', Auth::user()->id)->with('success', 'Candidate Updated');
            }
            //else display fail
            else{
                return back()->with('error','Failed to update profile!');
            }
        }

    }

    //Function to delete an application
    public function destroy($id)
    {
        $candidate = User::findOrFail($id);
        $result = $candidate->delete();
        $info = CandidateInfo::where('user_id', $id)->first()->delete();

        //If deletion of data is successful return to previous page with successful message
        if ($result){
            return redirect('candidate')->with('success', 'Candidate deleted');
        }
        //else display fail
        else{
            return back()->with('error','Failed to delete!');
        }
    }
}

resources/views/candidate/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 custom-padding">
            <div class="panel panel-default">
                <div class="panel-heading">Candidates
                    <!-- <a href="{{ route('candidate.create') }}" class="btn btn-primary btn-sm pull-right">Add </a> -->
                </div>
                <div class="search panel-body text-center">
                    {!! Form::open([
                            'url' => 'candidate/search',
                            'class' => 'form-horizontal',
                            'role' => 'form',
                            'method' => 'POST'
                            ]) !!}
                        <input type="text" name="search" placeholder="Search Candidates...">
                        <input type="hidden" name="type" value="{{ $type }}">
                    {!! Form::close() !!}
                </div>
                <div class="panel-body table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Candidate Name</th>
                                <th>Candidate Last Name</th>
                                <th><div class="pull-right">Actions</div></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($candidates as $candidate)
                            <tr>
                                <td><a href="{{ route('candidate.show', $candidate->id) }}"><div>{{ $candidate->first_name }}</div></a></td>
                                <td><a href="{{ route('candidate.show', $candidate->id) }}"><div>{{ $candidate->last_name }}</div></a></td>
                                <td>
                                    <div class="pull-right">
                                    <a href="{{ route('candidate.edit', $candidate->id) }}"><span class="fa fa-pencil"></span>
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td>No Candidates</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    <div>
                        {{ $candidates->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/candidate/search.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 custom-padding">
            <div class="panel panel-default">
                <div class="panel-heading"> Search Candidates

                    <a href="{{ route('candidate.index') }}" class="btn btn-primary btn-sm pull-right"> Back to Candidates page </a>
                </div>
                <div class="panel-body text-center">
                    <h3>Search results for <b>"{!! $searchTerm !!}"</b></h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Candidate Name</th>
                                <th>Candidate Last Name</th>
                                <th><div class="pull-right">Actions</div></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($candidates as $candidate)
                            <tr>
                                <td><a href="{{ route('candidate.show', $candidate->id) }}"><div>{{ $candidate->first_name }}</div></a></td>
                                <td><a href="{{ route('candidate.show', $candidate->id) }}"><div>{{ $candidate->last_name }}</div></a></td>
                                <td>
                                    <div class="pull-right">
                                    <a href="{{ route('candidate.edit', $candidate->id) }}"><span class="fa fa-pencil"></span>
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td>No Candidates</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    <div class="pull-right">
                        {{ $candidates->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/candidate/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 custom-padding">
            <div class="panel panel-default">
                <?php
                    if (Auth::user()->user_type_id == 4)
                    {
                        if ($candidate->user_type == 1){
                            ?>
                                <div class="panel-heading"><a href="/candidate">Candidates</a> <span class="fa fa-chevron-right"></span> {{ $candidate->first_name }} {{ $candidate->last_name }}
                                    <a href="{{ route('candidate.edit', $candidate->id) }}" class="btn btn-primary btn-sm pull-right">Edit </a>
                                </div>
                            <?php
                        }
                        else{
                            ?>
                                <div class="panel-heading"><a href="/recruited-candidate">Recruited Candidates</a> <span class="fa fa-chevron-right"></span> {{ $candidate->first_name }} {{ $candidate->last_name }}
                                    <a href="{{ route('candidate.edit', $candidate->id) }}" class="btn btn-primary btn-sm pull-right">Edit </a>
                                </div>
                            <?php
                        }
                    }
                    else{
                        ?>
                            <div class="panel-heading">My Profile
                                <a href="{{ route('candidate.edit', $candidate->id) }}" class="btn btn-primary btn-sm pull-right">Edit </a>
                            </div>
                        <?php
                    }
                 ?>
                <div class="panel-body">
                    <?php
                        if (Auth::guest() != true){
                            if (Auth::user()->user_type_id == 4 ){
                                if ($candidate->user_type == 1){
                                    ?>
                                    {!! Form::open([
                                        'route' => ['candidate.email', $candidate->id],
                                        'class' => 'form-horizontal'
                                    ]) !!}
                                        <div>
                                            <button type="submit" class="btn btn-primary">Recruit</button>
                                        </div>
                                    {!! Form::close() !!}
                                    <?php
                                }
                            }
                        }
                     ?>
                 </div>
                <div class="panel-body">
                    <div>
                        <table class="table table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th><div class="text-right">Candidate</th>
                                    <th>#{{ $candidate->id }}</th>
                                <tr>
                            </thead>
                            <tbody>
                                                                
                                <tr>
                                    <td><div class="text-right"><strong>First Name</strong></div></td>
                                    <td>{{ $candidate->first_name }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Last Name</strong></div></td>
                                    <td>{{ $candidate->last_name }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>National Identity Card Number</strong></div></td>
                                    <td>{{ $candidate->nic }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Gender</strong></div></td>
                                    <td><div class="text-capitalize">{{ $candidate->gender }}</div></td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Date of Birth</strong></div></td>
                                    <td>{{ $candidate->dob }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Marital Status</strong></div></td>
                                    <td><div class="text-capitalize">{{ $candidate->marital_status }}</div></td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Address</strong></div></td>
                                    <td><address>{{ $candidate->address }}</address></td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Phone Number</strong></div></td>
                                    <td>{{ $candidate->phone_number }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Mobile Number</strong></div></td>
                                    <td>{{ $candidate->mobile_number }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>E-mail Address</strong></div></td>
                                    <td>{{ $candidate->email }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>CV</strong></div></td>
                                    <td><a href="/documents/cv/{{ $candidate->cv }}">{{ $candidate->cv }}</a></td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Certificates</strong></div></td>
                                    <td><a href="#">Certificates.pdf</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php
                    if (Auth::guest() != true){
                        if (Auth::user()->user_type_id == 4){
                            ?>
                                <div class="panel-footer">
                                    {!! Form::open([
                                        'route' => ['candidate.destroy', $candidate->id],
                                        'method' => 'delete',
                                        'class' => 'form-horizontal'
                                    ]) !!}
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    {!! Form::close() !!}
                                </div>
                            <?php
                        }
                    }
                 ?>
            </div>
        </div>
    </div>
</div>
@endsection