routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('/position', 'PositionController');

Route::resource('/vacancy', 'VacancyController');
//Route::get('/vacancy/search', 'VacancyController@search');
Route::post('/vacancy/search', 'VacancyController@search');

Route::post('/candidate/search', 'CandidateController@search');

Route::resource('/candidate', 'CandidateController');

Route::get('/recruited-candidate', 'CandidateController@recruitedCandidate');

Route::resource('/interview-type', 'InterviewTypeController');

Route::resource('/user-type', 'UserTypeController');

Route::resource('/recruiter', 'RecruiterController');

Route::resource('/application', 'ApplicationController');

Route::resource('/interview', 'InterviewController');

Route::get('/interview/create/{id?}', 'InterviewController@create');

Route::post('candidate/{id}/email', 'CandidateController@email')->name('candidate.email');

Route::get('interview/{id}/conduct', 'InterviewController@conduct')->name('interview.conduct');

Route::get('candidate-interview/{id}', 'InterviewController@candidateInterview');

app/Application.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Application extends Model
{
    use SoftDeletes;

    public $timestamps = false;

    protected $fillable = [
        'candidate_id',
        'vacancy_id',
        'date_applied',
        'overall_rating'
    ];

    public function candidate(){
        return $this->hasOne('App\User', 'id', 'candidate_id');
    }

    public function vacancy(){
        return $this->hasOne('App\Vacancy', 'id', 'vacancy_id');
    }
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use View;
use App\Application;
use App\Http\Requests\ApplicationRequest;
use Auth;

class ApplicationController extends Controller
{

    // Returns index View
    public function index()
    {
        //If User is a candidate, return only applications for that specific candidate only
        if (Auth::user()->user_type_id == 1){
            $applications = Application::where('candidate_id', '=', Auth::id())->paginate(10);
            return view('application.index', compact('applications'));
        }
        //else return all applications
        else{
            $applications = Application::paginate(10);
            return view('application.index', compact('applications'));
        }
    }

    //Returns Create View
    public function create()
    {
        return view('application.create');
    }

    //Data from the form in create view uses the store function to store data in the database
    public function store(ApplicationRequest $request)
    {
        //Allow only users who have not applied for a job to apply for a job
        if (Application::where('candidate_id',$request['candidate_id'])->where('vacancy_id', $request['vacancy_id'])->count() == 0){
            $application = Application::create([
                'candidate_id' => $request['candidate_id'],
                'vacancy_id' => $request['vacancy_id'],
                'date_applied' => date("Y/m/d"),
                'overall_rating' => '0'
            ]);
            //If submission of data is successful return to previous page with successful message
            if ($application){
                return back()->with('success', 'You have Successfully applied for this vacancy.');
            }
            //else display fail
            else{
                return back()->with('error','Failed to save!');
            }
        }
        //If users already applied for job, return this message
        else{
            return back()->with('error','You have already applied for this job!');
        }
    }

    //Returns the show view of the appropriate application
    public function show($id)
    {
        $application = Application::findOrFail($id);
        return view('application.show', compact('application'));
    }

    //Returns the Edit view of the appropriate application
    public function edit($id)
    {
        $application = Application::findOrFail($id);
        return view('application.edit', compact('application'));
    }

    //Data from the form in the Edit view uses the update function to update data in the database
    public function update(ApplicationRequest $request, $id)
    {
        $application = Application::findOrFail($id);
        $result = $application->update($request->all());
        //If submission of data is successful return to previous page with successful message
        if ($result){
            return redirect('application')->with('success', 'Application Updated');
        }
        //else display fail
        else{
            return back()->with('error','Failed to update!');
        }
    }

    //Function to delete an application
    public function destroy($id)
    {
        $application = Application::findOrFail($id);
        $result = $application->delete();
        //If deletion of data is successful return to previous page with successful message
        if ($result){
            return redirect('application')->with('success', 'Application deleted');
        }
        //else display fail
        else{
            return back()->with('error','Failed to delete!');
        }
    }
}

resources/views/application/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 custom-padding">
            <div class="panel panel-default">
                <div class="panel-heading">Add New Application</div>
                <div class="panel-body">

                    {!! Form::open([
                      'route' => 'application.store',
                      'class' => 'form-horizontal',
                      'role' => 'form',
                      'method' => 'POST',
                      ]) !!}

                        <!-- candidate id   -->
                        <div class="form-group{{ $errors->has('candidate_id') ? ' has-error' : '' }}">
                            <div class="container-fluid">
                                {!! Form::label(
                                    'candidate_id',
                                    'Candidate',
                                    [
                                        'class' => 'col-md-4 control-label'
                                    ]
                                ); !!}

                                <div class="col-md-6">
                                    {!! Form::select(
                                        'candidate_id',
                                        App\User::select(DB::raw("CONCAT(first_name,' ',last_name) AS name"),'id')->pluck('name', 'id'),
                                        null,
                                        [
                                            'placeholder' => 'Select Candidate...',
                                            'class' => 'form-control'
                                        ]
                                    ); !!}
                                </div>
                            </div>
                            @if ($errors->has('candidate_id'))
                            <div class="container-fluid">
                                <div class="col-md-8 col-md-offset-4">
                                    <span class="help-block">
                                        <strong>{{ $errors->first('candidate_id') }}</strong>
                                    </span>
                                </div>
                            </div>
                            @endif
                        </div>

                        <!-- Vacancy id   -->
                        <div class="form-group{{ $errors->has('vacancy_id') ? ' has-error' : '' }}">
                            <div class="container-fluid">
                                {!! Form::label(
                                    'vacancy_id',
                                    'Vacancy',
                                    [
                                        'class' => 'col-md-4 control-label'
                                    ]
                                ); !!}

                                <div class="col-md-6">
                                    {!! Form::select(
                                        'vacancy_id',
                                        App\Vacancy::pluck('name', 'id'),
                                        null,
                                        [
                                            'placeholder' => 'Select Vacancy...',
                                            'class' => 'form-control'
                                        ]
                                    ); !!}
                                </div>
                            </div>
                            @if ($errors->has('vacancy_id'))
                            <div class="container-fluid">
                                <div class="col-md-8 col-md-offset-4">
                                    <span class="help-block">
                                        <strong>{{ $errors->first('vacancy_id') }}</strong>
                                    </span>
                                </div>
                            </div>
                            @endif
                        </div>

                        <!--Date Applied-->
                        <div class="form-group{{ $errors->has('date_applied') ? ' has-error' : '' }}">
                          <div class="container-fluid">
                              {!! Form::label(
                                  'date_applied',
                                  'Date Applied',
                                  [
                                      'class' => 'col-md-4 control-label'
                                  ]
                              ); !!}

                              <div class="col-md-4">
                                  {!! Form::date(
                                      'date_applied',
                                      old('date_applied'),
                                      [
                                          'class'=>'form-control',
                                      ]
                                  ); !!}
                              </div>
                          </div>
                          @if ($errors->has('date_applied'))
                          <div class="container-fluid">
                              <div class="col-md-8 col-md-offset-4">
                                  <span class="help-block">
                                      <strong>{{ $errors->first('date_applied') }}</strong>
                                  </span>
                              </div>
                          </div>
                          @endif
                        </div>

                        <!--Overall Rating-->
                        <div class="form-group{{ $errors->has('overall_rating') ? ' has-error' : '' }}">
                            <div class="container-fluid">
                                {!! Form::label(
                                    'overall_rating',
                                    'Overall Rating',
                                    [
                                        'class' => 'col-md-4 control-label'
                                    ]
                                ); !!}

                                <div class="col-md-3">
                                    <div class="input-group">
                                        {!! Form::number(
                                            'overall_rating',
                                            old('overall_rating'),
                                            [
                                                'class'=>'form-control',
                                                'step'=>'1',
                                                'min'=>'0',
                                                'max'=>'10',
                                                'required' => 'required'
                                            ]
                                        ); !!}
                                        <span class="input-group-addon" id="basic-addon2">/10</span>
                                    </div>
                                </div>
                            </div>
                            @if ($errors->has('overall_rating'))
                            <div class="container-fluid">
                                <div class="col-md-8 col-md-offset-4">
                                    <span class="help-block">
                                        <strong>{{ $errors->first('overall_rating') }}</strong>
                                    </span>
                                </div>
                            </div>
                            @endif
                        </div>

                        <!-- submit -->

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                {!! Form::submit(
                                    'Save',
                                    [
                                        'class' => 'btn btn-primary'
                                    ]
                                ); !!}

                            </div>
                        </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/application/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 custom-padding">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Application</div>
                <div class="panel-body">
                    {!! Form::open([
                        'route' => ['application.update', $application->id],
                        'class' => 'form-horizontal',
                        'role' => 'form',
                        'method' => 'put'
                    ]) !!}

                    <!-- candidate id   -->
                    <div class="form-group{{ $errors->has('candidate_id') ? ' has-error' : '' }}">
                        <div class="container-fluid">
                            {!! Form::label(
                                'candidate_id',
                                'Candidate',
                                [
                                    'class' => 'col-md-4 control-label'
                                ]
                            ); !!}

                            <div class="col-md-6">
                                {!! Form::select(
                                    'candidate_id',
                                    App\User::select(DB::raw("CONCAT(first_name,' ',last_name) AS name"),'id')->pluck('name', 'id'),
                                    $application->candidate_id,
                                    [
                                        'placeholder' => 'Select Candidate...',
                                        'class' => 'form-control',
                                        'disabled' => 'disabled'
                                    ]
                                ); !!}
                            </div>
                        </div>
                        @if ($errors->has('candidate_id'))
                        <div class="container-fluid">
                            <div class="col-md-8 col-md-offset-4">
                                <span class="help-block">
                                    <strong>{{ $errors->first('candidate_id') }}</strong>
                                </span>
                            </div>
                        </div>
                        @endif
                    </div>

                    <!-- Vacancy id   -->
                    <div class="form-group{{ $errors->has('vacancy_id') ? ' has-error' : '' }}">
                        <div class="container-fluid">
                            {!! Form::label(
                                'vacancy_id',
                                'Vacancy',
                                [
                                    'class' => 'col-md-4 control-label'
                                ]
                            ); !!}

                            <div class="col-md-6">
                                {!! Form::select(
                                    'vacancy_id',
                                    App\Vacancy::pluck('name', 'id'),
                                    $application->vacancy_id,
                                    [
                                        'placeholder' => 'Select Vacancy...',
                                        'class' => 'form-control'
                                    ]
                                ); !!}
                            </div>
                        </div>
                        @if ($errors->has('vacancy_id'))
                        <div class="container-fluid">
                            <div class="col-md-8 col-md-offset-4">
                                <span class="help-block">
                                    <strong>{{ $errors->first('vacancy_id') }}</strong>
                                </span>
                            </div>
                        </div>
                        @endif
                    </div>

                    <!--Date Applied-->
                    <div class="form-group{{ $errors->has('date_applied') ? ' has-error' : '' }}">
                      <div class="container-fluid">
                          {!! Form::label(
                              'date_applied',
                              'Date Applied',
                              [
                                  'class' => 'col-md-4 control-label'
                              ]
                          ); !!}

                          <div class="col-md-4">
                              {!! Form::date(
                                  'date_applied',
                                  $application->date_applied,
                                  [
                                      'class'=>'form-control',
                                  ]
                              ); !!}
                          </div>
                      </div>
                      @if ($errors->has('date_applied'))
                      <div class="container-fluid">
                          <div class="col-md-8 col-md-offset-4">
                              <span class="help-block">
                                  <strong>{{ $errors->first('date_applied') }}</strong>
                              </span>
                          </div>
                      </div>
                      @endif
                    </div>

                    <!--Overall Rating-->
                    <div class="form-group{{ $errors->has('overall_rating') ? ' has-error' : '' }}">
                        <div class="container-fluid">
                            {!! Form::label(
                                'overall_rating',
                                'Overall Rating',
                                [
                                    'class' => 'col-md-4 control-label'
                                ]
                            ); !!}

                            <div class="col-md-3">
                                <div class="input-group">
                                    {!! Form::number(
                                        'overall_rating',
                                        $application->overall_rating,
                                        [
                                            'class'=>'form-control',
                                            'step'=>'1',
                                            'min'=>'0',
                                            'max'=>'10',
                                            'required' => 'required'
                                        ]
                                    ); !!}
                                    <span class="input-group-addon" id="basic-addon2">/10</span>
                                </div>
                            </div>
                        </div>
                        @if ($errors->has('overall_rating'))
                        <div class="container-fluid">
                            <div class="col-md-8 col-md-offset-4">
                                <span class="help-block">
                                    <strong>{{ $errors->first('overall_rating') }}</strong>
                                </span>
                            </div>
                        </div>
                        @endif
                    </div>

                    <!-- submit button -->
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            {!! Form::submit(
                                'Save',
                                [
                                    'class' => 'btn btn-primary'
                                ]
                            ); !!}

                        </div>
                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/application/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 custom-padding">
            <div class="panel panel-default">
                <div class="panel-heading"><a href="/application">Applications</a> <span class="fa fa-chevron-right"></span> Application # {{ $application->id }}
                    <?php
                        if (Auth::guest() != true){
                            if (Auth::user()->user_type_id == 4){
                                ?>
                                    <a href="{{ route('application.edit', $application->id) }}" class="btn btn-primary btn-sm pull-right">Edit </a>
                                <?php
                            }
                        }
                     ?>
                </div>
                <div class="panel-body">
                    <div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th><div class="text-right">Application</th>
                                    <th>#{{ $application->id }}</th>
                                <tr>
                            </thead>

                            <tbody>
                                <tr>
                                    <td><div class="text-right"><strong>Candidate Name</strong></div></td>
                                    <td><a href="{{ route('candidate.show', $application->candidate->id) }}">{{ $application->candidate->first_name }} {{ $application->candidate->last_name }}</a></td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Job Title</strong></div></td>
                                    <td><a href="{{ route('vacancy.show', $application->vacancy->id) }}">{{ $application->vacancy->name }}</a></td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Date of Application</strong></div></td>
                                    <td>{{ $application->date_applied }}</td>
                                </tr>

                                <tr>
                                    <td><div class="text-right"><strong>Vacancy Closing Date</strong></div></td>
                                    <td>{{ $application->vacancy->closing_date }}</td>
                                </tr>

                                <?php
                                    if (Auth::guest() != true){
                                        if (Auth::user()->user_type_id == 4){
                                            ?>
                                                <tr>
                                                    <td><div class="text-right"><strong>Interviews</strong></div></td>
                                                    <td>
                                                        <a href="/candidate-interview/{{$application->id}}">{{ DB::table('interviews')->where('application_id', $application->id)->count() }} Interviews</a>

                                                        <a href="/interview/create/{{$application->id}}" class="btn btn-primary btn-sm ">Add Interview </a>

                                                    </td>
                                                </tr>
                                            <?php
                                        }
                                    }
                                 ?>

                                <?php
                                    if (Auth::guest() != true){
                                        if (Auth::user()->user_type_id == 4){
                                            ?>
                                                <tr>
                                                    <td><div class="text-right"><strong>Overall Rating</strong></div></td>
                                                    <?php $avg = DB::table('interviews')->where('application_id', $application->id)->where('status', '=', 'Done')->avg('rating'); ?>
                                                    <td>{{ round($avg,2) }}/10</td>
                                                </tr>
                                            <?php
                                        }
                                    }
                                 ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php
                    if (Auth::guest() != true){
                        if (Auth::user()->user_type_id == 4){
                            ?>
                                <div class="panel-footer">

                                    {!! Form::open([
                                        'route' => ['application.destroy', $application->id],
                                        'method' => 'delete',
                                        'class' => 'form-horizontal'
                                    ]) !!}

                                    <button type="submit" class="btn btn-danger">
                                        Delete
                                    </button>

                                    {!! Form::close() !!}

                                </div>
                            <?php
                        }
                    }
                 ?>
            </div>
        </div>
    </div>
</div>
@endsection